### ISSUE TITLE
Missing package_ca

### ISSUE THREAD

**Issue by planemad** [mapillary/mapillary_sprite_source#4]
From https://github.com/mapbox/osm-navigation-map/issues/38#issuecomment-235245706

Noticed that the [sprites.json](https://www.mapillary.com/sprites/sprites.json) don't have values for signs detected by the Canada package. Will this be coming soon?

cc @knikel @gyllen 

Here is the list of signs in the Canada package:

- [x] mandatory--pass-on-either-side--ca
- [x] regulatory--maximum-speed-limit-100--ca
- [x] regulatory--maximum-speed-limit-110--ca
- [x] regulatory--maximum-speed-limit-120--ca
- [x] regulatory--maximum-speed-limit-5--ca
- [x] regulatory--maximum-speed-limit-10--ca
- [x] regulatory--maximum-speed-limit-15--ca
- [x] regulatory--maximum-speed-limit-20--ca
- [x] regulatory--maximum-speed-limit-25--ca
- [x] regulatory--maximum-speed-limit-30--ca
- [x] regulatory--maximum-speed-limit-35--ca
- [x] regulatory--maximum-speed-limit-40--ca
- [x] regulatory--maximum-speed-limit-45--ca
- [x] regulatory--maximum-speed-limit-50--ca
- [x] regulatory--maximum-speed-limit-55--ca
- [x] regulatory--maximum-speed-limit-60--ca
- [x] regulatory--maximum-speed-limit-65--ca
- [x] regulatory--maximum-speed-limit-70--ca
- [x] regulatory--maximum-speed-limit-75--ca
- [x] regulatory--maximum-speed-limit-80--ca
- [x] regulatory--maximum-speed-limit-85--ca
- [x] regulatory--maximum-speed-limit-90--ca
- [x] regulatory--no-bicycles--ca
- [x] regulatory--no-entry--ca
- [x] regulatory--no-heavy-goods-vehicles--ca
- [x] regulatory--no-left-turn--ca
- [x] regulatory--no-motor-vehicles--ca
- [x] regulatory--no-motorcycles--ca
- [x] regulatory--no-overtaking--ca
- [x] regulatory--no-parking--ca
- [x] regulatory--no-pedestrians--ca
- [x] regulatory--no-right-turn--ca
- [x] regulatory--no-stopping--ca
- [x] regulatory--no-u-turn--ca
- [x] regulatory--stop--ca
- [x] regulatory--yield--ca
- [x] warning--bump-in-road--ca
- [x] warning--crossroads-ahead--ca
- [x] warning--crossroads-ahead--ca--ontario
- [x] warning--curve-left-ahead--ca
- [x] warning--curve-left-ahead--ca--ontario
- [x] warning--curve-right-ahead--ca
- [x] warning--curve-right-ahead--ca--ontario
- [x] warning--cyclists-crossing--ca
- [x] warning--dip-in-road--ca
- [x] warning--divided-highway-ahead--ca
- [x] warning--divided-highway-ends--ca
- [x] warning--domestic-animals--ca
- [x] warning--double-curve-first-left-ahead--ca--ontario
- [x] warning--double-curve-first-right-ahead--ca--ontario
- [x] warning--double-turn-first-left-ahead--ca
- [x] warning--double-turn-first-right-ahead--ca
- [x] warning--emergency-vehicles--ca
- [x] warning--equestrians--ca
- [x] warning--falling-rocks-or-debris-right--ca
- [x] warning--farm-vehicles--ca
- [x] warning--hairpin-curve-right-ahead--ca
- [x] warning--hairpin-curve-right-ahead--ca--ontario
- [x] warning--height-restriction-ahead--ca--feet
- [x] warning--height-restriction-ahead--ca--meters
- [x] warning--junction-with-a-side-road-perpendicular-left-ahead--ca
- [x] warning--junction-with-a-side-road-perpendicular-left-ahead--ca--ontario
- [x] warning--junction-with-a-side-road-perpendicular-right-ahead--ca
- [x] warning--junction-with-a-side-road-perpendicular-right-ahead--ca--ontario
- [x] warning--level-railroad-crossing-with-barriers-ahead--ca
- [x] warning--loose-road-surface--ca
- [x] warning--narrow-bridge-ahead--ca
- [x] warning--opening-or-swing-bridge--ca
- [x] warning--pavement-ends--ca
- [x] warning--pedestrian-crossing--ca
- [x] warning--pedestrian-crossing--ca--quebec
- [x] warning--playground-ahead--ca
- [x] warning--road-narrows-ahead--ca
- [x] warning--road-narrows-left-ahead--ca
- [x] warning--road-narrows-right-ahead--ca
- [x] warning--roundabout-ahead--ca
- [x] warning--shared-road-motocycles-cyclists--ca
- [x] warning--slippery-road-surface--ca
- [x] warning--steep-hill-downwards--ca
- [x] warning--steep-hill-upwards--ca
- [x] warning--stop-ahead--ca
- [x] warning--stop-ahead--ca--ontario
- [x] warning--traffic-merges-left-ahead--ca
- [x] warning--traffic-merges-left-ahead--ca--ontario
- [x] warning--traffic-merges-right-ahead--ca
- [x] warning--traffic-merges-right-ahead--ca--ontario
- [x] warning--traffic-signals-ahead--ca
- [x] warning--tunnel-ahead--ca
- [x] warning--turn-left--ca
- [x] warning--turn-right--ca
- [x] warning--two-way-traffic-ahead--ca
- [x] warning--uncontrolled-railroad-crossing-ahead--ca
- [x] warning--uneven-road--ca
- [x] warning--wild-animals--ca
- [x] warning--winding-road-first-left-ahead--ca
- [x] warning--winding-road-first-right-ahead--ca
- [x] warning--workers-in-road-ahead--ca
- [x] warning--yield-ahead--ca

**Comment by ybkuang** [comment]
@planemad I added the signs in Canada package to your comment. We will be working on add these as well in coming weeks. It will be great to have your contributions here too!

**Comment by knikel** [comment]
@planemad We've added all the Canadian signs, rename `package_ui` and `package_mapbox` to `bak_ui` and `bak_mapbox` and run `npm run build:all` to get sprites with just the traffic signs.
