### ISSUE TITLE
Transparent background in turn restriction signs

### ISSUE THREAD

**Issue by GITNE** [mapillary/mapillary_sprite_source#7]
The EU left and right turn restriction signs (with wing arrows) have a transparent background instead of opaque white. See here:
![broken eu left turn restriction sign](https://cloud.githubusercontent.com/assets/15823872/25797272/c3d42eea-33dc-11e7-8828-0f88fad4916a.png)
![broken eu right turn restriction sign](https://cloud.githubusercontent.com/assets/15823872/25797271/c3d381f2-33dc-11e7-8093-ffdc8bdede94.png)

See also Mapillary issue: mapillary/mapillary_issues/issues/2545

**Comment by ybkuang** [comment]
@GITNE we will fix that.
